# Generated by Django 5.1.1 on 2024-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_productimages_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_items",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
