# Generated by Django 5.1.1 on 2024-09-30 00:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="This is the product description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="I am the nestify vendor, trustworthy", null=True
            ),
        ),
    ]
