# Generated by Django 5.1.1 on 2024-10-23 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_cart_cartitem_cart_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorder",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cartorderitems",
            name="image",
        ),
        migrations.RemoveField(
            model_name="cartorderitems",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cartorderitems",
            name="total",
        ),
        migrations.AddField(
            model_name="cartorder",
            name="items",
            field=models.ManyToManyField(
                through="core.CartOrderItems", to="core.product"
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.product"
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="core.product",
            ),
        ),
    ]
