# Generated by Django 5.1.1 on 2024-10-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_cartorder_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addressbook",
            old_name="status",
            new_name="is_default",
        ),
        migrations.AddField(
            model_name="addressbook",
            name="city",
            field=models.CharField(default="Ekpoma", max_length=100),
        ),
        migrations.AddField(
            model_name="addressbook",
            name="mobile",
            field=models.CharField(default="09030748341", max_length=200),
        ),
        migrations.AddField(
            model_name="addressbook",
            name="state",
            field=models.CharField(default="Edo State", max_length=100),
        ),
        migrations.AlterField(
            model_name="addressbook",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
