# Generated by Django 5.1.1 on 2024-10-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_user_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Contact Us",
            },
        ),
    ]
